#SPDX-License-Identifier: MIT-0
---
# vars file for application-seafile-client

seafile_installation_dir: ~/seafile

seafile_installation_desktop_name: seafile_desktop
seafile_installation_drive_name: seafile_drive