#SPDX-License-Identifier: MIT-0
---

# TODO:
# Stelle sicher, dass package_manager_short_name existiert und nicht leer ist.

- name: Get vscode package name
  set_fact:
    vscode_package_name: "{{ vars['vscode-package-name-' + package_manager_short_name] }}"
    
- name: Check for installed package  - found
  ansible.builtin.debug:
    msg: "found: {{ vscode_package_name }}"

- name: Install vscode
  ansible.builtin.include_tasks: "vscode-{{ package_manager_short_name }}.yml"

  
    